// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShippingCostCalculator.Data.Models;

public partial class Country
{
    public int CountryId { get; set; }

    public string CountryName { get; set; }

    public decimal TaxRate { get; set; }

    public decimal BaseShippingCost { get; set; }
}